import Head from 'next/head'
import HeaderLogin from '../../src/components/headerLogin'
import styles from '../../styles/Estudante.module.css'

const Estudante = () => {
  
  
  return (
    <>
      <Head>
        <title>Dualidade | Estudante</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeaderLogin user="Luiz"/>

        <section className={styles.section}>
          <div className={styles.container}> 
            <h2>Você pode atualizar seu perfil agora mesmo</h2>
            <p>Esteja pronto, pois nunca se sabe a hora que uma oportunidade pode aparecer</p>
            <button>Atualizar</button>
          </div>

          <div className={styles.container}>
            <h2>Confira Algumas tarefas que se adequam ao seu perfil</h2>
          </div>
          <div className={styles.cards}>
            <div className={styles.card}>
              <h3 className={styles.h3}>Sistema interno de Logística</h3>
              <h4 className={styles.h4}>Mariana LocaMoveís</h4>
              <p className={styles.p}>Tenho interese em um sistema de logística personalizado para controlar a entrada e saída de moveís do estoque.</p>
              <button className={styles.button}>Saíba mais</button>
            </div>
            <div className={styles.card}>
              <h3 className={styles.h3}>Site de vendas</h3>
              <h4 className={styles.h4}>Oficina do Tião</h4>
              <p className={styles.p}>A procura de um desenvolvedor para criar um site da oficina com venda de peças e serviço de atendimento ao cliente.</p>
              <button className={styles.button}>Saíba mais</button>
            </div>
          </div>
        </section>
      </main>
    </>
  ); 
}

export default Estudante;