import Head from 'next/head'
import HeaderLogin from '../../src/components/headerLogin'
import styles from '../../styles/Estudante.module.css'

const Empresa = () => {
  
  
  return (
    <>
      <Head>
        <title>Dualidade | Empresa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderLogin />

      <main>
        <HeaderLogin user="Mariana"/>

        <section className={styles.section}>
          <div className={styles.container}>
            <h2>Confira alguns desenvolvedores que se adequam a sua necessidade</h2>
          </div>
          <div>

          </div>
        </section>
      </main>
    </>
  ); 
}

export default Empresa;